from setuptools import setup, find_packages

setup(
    name="medical_image_tools_yzdn",
    #version="0.1.0",
    author="Yazdan Salimi",
    author_email="salimiyazdan@gmail.com",
    description="functions to facilitate daily reaseach and clinical medical image processing tasks",
    long_description=open('README.md').read(),
    long_description_content_type="text/markdown",
    url="https://github.com/YazdanSalimi/medical-image-processing-tools",
    packages=find_packages(),
    py_modules=["dicom", "image", "radiomics", "image_regression_DL_inference"],
    install_requires=[
        "pandas",
        "tqdm",
        "termcolor",
        "glob2", 
        "torch",
        "SimpleITK",
        "multiprocess",
        "numpy", 
        "natsort", 
        "batchgenerators",
        "monai", 
        "nibabel", 
        "pyradiomics",
        "six",
        "pydicom",
        "scipy==1.11.4",
        "opencv-python", 
    ],
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires='>=3.6',
)
